# Generated by Django 3.2.3 on 2021-05-20 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_path', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('vote_average', models.IntegerField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('adult', models.BooleanField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, max_length=20, null=True)),
                ('original_title', models.TextField(blank=True, null=True)),
                ('rating_average', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=50, unique=True)),
                ('iso_639_1', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('movies', models.ManyToManyField(related_name='spoken_languages', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.CharField(max_length=20, unique=True)),
                ('name', models.TextField()),
                ('movies', models.ManyToManyField(related_name='production_countries', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('logo_path', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('origin_country', models.TextField(blank=True, null=True)),
                ('movies', models.ManyToManyField(related_name='production_companies', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('movies', models.ManyToManyField(related_name='genres', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='BelongsToCollection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('poster_path', models.TextField(blank=True, null=True)),
                ('backdrop_path', models.TextField(blank=True, null=True)),
                ('movies', models.ManyToManyField(related_name='belongs_to_collections', to='movies.Movie')),
            ],
        ),
    ]
